### ISSUE TITLE
chlauncher does not download any file from Github

### ISSUE THREAD

**Issue by woolyss** [henrypp/chrlauncher#95] opened 2018-02-24 16:26 UTC
Hello Henry++ ;)

Today, Rudolph a user (https://chromium.woolyss.com/#comment-3009) reported to me that Chrlauncher does not download any file.

> The chrlauncher opens, but no download. Clicking on Download update does nothing.

**The issue concerns files/binaries stored at Github.**

I checked all and I think there is an issue with your tool.

- My API is ok --> **GOOD**
test: https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=stable-codecs-sync&out=json

- The file exists --> **GOOD**
test: https://github.com/henrypp/chromium/releases/download/v64.0.3282.186-r520840-win64/chromium-sync.zip

- The download is possible with [wget](https://eternallybored.org/misc/wget/) on win7 x64 --> **GOOD**
It means there is no Github restriction.
test: https://i.imgur.com/rqCU3iP.png

-  Github site --> **GOOD**
https://status.github.com/

-  Chrlauncher opens --> **GOOD**

-  Chrlauncher downloads --> **BAD**

--------------

### EDIT February 27, 2018
As @truboxl said:
> Monitoring with Resource Monitor seems like it never get past AWS (assuming Github)

I agree, it seems to be a problem with Amazon Web Services (AWS). This is the cloud computing used for Github files/binaries.

--------------

### EDIT February 28, 2018

On Windows 7 x64, chrlauncher 2.3 works normally. So just replace the chrlauncher executable (.EXE)! ^^

If you want to stay with chrlauncher 2.4.1, you must use the manual way! :/
(My screenshot: https://i.imgur.com/LpMo2Pq.png)
1. Unzip the corresponding Chromium Archive (ZIP) and rename the unzipped folder as "bin".
2. Replace the old folder by the new one, in the main Chrlauncher folder.
3. Enjoy!

Your all data are in the "profile" folder. DO NOT REMOVE this folder.

--------------

## How to force to open Chromium within chrlauncher?
Set `ChromiumCheckPeriod=0` in the **chrlauncher.ini** file.
It will disable update checking. So Chromium will open ! ^^

--------------

Regards,

**Comment by felipeportella** [comment] 2018-02-25 02:12
I'm facing the same problem in Win7Pro ... I did the same test described here with same behaviour.

**Comment by kanink007** [comment] 2018-02-25 03:57
oh good thing im not the only one.
since the new version (v186 in the end) was detected today, my chr launcher didnt download. even pressing download button didnt help.

**Comment by truboxl** [comment] 2018-02-26 12:11
dev-official works though for downloading and extracting the files so I dunno what's the problem with the other builds...

Monitoring with Resource Monitor seems like it never get past AWS (assuming Github)

There aren't really any difference between [dev-offical URL](https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=dev-official&out=json) and [dev-codecs-sync URL](https://chromium.woolyss.com/api/v3/?os=windows&bit=64&type=dev-codecs-sync&out=json) except for the missing repository and commit variables (actual input is in string form but shown here is json form for explanation)

**Comment by tomasz1986** [comment] 2018-02-27 15:14
Has the problem been fixed? I am using the launcher to download the stable-codecs-nosync version right now, and it seems to be working fine (although very slowly).

![chrlauncher](https://user-images.githubusercontent.com/5626656/36736562-49384aee-1c1c-11e8-8608-7fe4f195bf55.png)

**Comment by tomasz1986** [comment] 2018-02-28 05:17
Well, it is downloading for me though. Maybe it is a regional thing? The exact server IP where the file is being downloaded from here is https://ipinfo.io/52.216.0.40.

**Comment by lpohl** [comment] 2018-02-28 09:43
For me the problem is not fixed in the current version, but the 2.3 version of the chrlauncher binary is working just fine!?

**Comment by woolyss** [comment] 2018-02-28 18:54
Yes, I agree with you guys.
- On win7 x64,  chrlauncher 2.4.1 **does not download files from Github**. But chrlauncher 2.3 works.
- On win10 x64,  chrlauncher 2.4.1 works.

**Comment by truboxl** [comment] 2018-03-02 04:14
@smorks Confirmed! The listed update / registry fix / easy fix for Windows 7 provided in the section does fix the problem. Looks like Windows 7 components are getting old and require push ups...

**Comment by henrypp** [comment] 2018-03-02 05:43
DONE!

**Closed by henrypp** 2018-03-02 05:43 UTC

**Comment by tomasz1986** [comment] 2018-03-02 07:10
I am not sure if the problem is related, but the newest version (v2.4.2) does not work for me in Windows 10 x86 2016 LTSB (have not tested other OSes).

In the beginning, it seems to start downloading normally, but then the progress bar goes crazy, refreshes rapidly several times, and the file size values below it show unreal numbers (e.g. 3GB / 70MB).

After a few seconds everything stops, but the browser is still not installed, and the download button is grayed out.

No such issues with v2.4.1.

**Comment by henrypp** [comment] 2018-03-02 08:04
@tomasz1986, fixed

**Comment by woolyss** [comment] 2018-03-02 23:57
Thank you very much Henry++
chrlauncher works nicely! ;)

**Comment by tomasz1986** [comment] 2018-03-03 07:11
Thank you. I can confirm that the launcher downloads fine now :thumbsup:
